name: Save CloudFormation template
# based on https://github.com/AdminTurnedDevOps/YouTube/blob/main/.github/workflows/main.yml

on:
  # When it works, uncomment these 2 lines:
  # release:
  #   types: [published]
  push:
    branches:
      - CF-artifact

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CDK_DEFAULT_ACCOUNT: "123456789012"
  CDK_DEFAULT_REGION: "eu-central-1"

jobs:
  aws_cdk:  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install npm
        uses: actions/setup-node@v3

      - name: Install AWS CDK
        run: 'npm install -g aws-cdk'

      - name: Install Requirements
        run: 'pip3 install -r requirements.txt'

      - name: Create config file
        run: |-
          cat <<EOF > ~/.aws/config
          [default]
          region = eu-central-1
          EOF

      - name: Run CDK synth
        run: 'cdk synth'

      - name: Save CloudFormation template
        uses: actions/upload-artifact@v3
        with:
          name: ec2-instance.template.json
          path: ./cdk.out/ec2-instance.template.json
